# Generated by Django 4.2.3 on 2023-08-03 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=150)),
                ('patient_mobile', models.CharField(max_length=12)),
                ('doctor', models.CharField(max_length=50)),
                ('patient_problem', models.TextField(max_length=210)),
                ('selected_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
