# Generated by Django 4.2.3 on 2023-08-04 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cureya', '0003_section_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='title',
        ),
        migrations.AddField(
            model_name='section',
            name='content_type',
            field=models.CharField(choices=[('P', 'Paragraph'), ('B', 'Bullet')], default='LG', max_length=1),
        ),
        migrations.AddField(
            model_name='section',
            name='section_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='section',
            name='section_size',
            field=models.CharField(choices=[('SM', 'SMALL'), ('LG', 'LARGE')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='section',
            name='team_mate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cureya.teammember'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='team/'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cureya.section')),
            ],
        ),
    ]
