# Generated by Django 4.2.3 on 2023-08-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureya', '0004_remove_section_title_section_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(max_length=555),
        ),
    ]
