# Generated by Django 4.2.3 on 2023-08-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureya', '0005_alter_content_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
