# Generated by Django 4.2.3 on 2023-08-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureya', '0007_alter_section_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishBookResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=110)),
                ('phone', models.CharField(max_length=14)),
                ('publish_information', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
