# Generated by Django 4.2.3 on 2023-08-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureya', '0008_publishbookresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='priority',
            field=models.IntegerField(default=3),
        ),
    ]
